# -*- coding: utf-8 -*-
"""BackgroundColor_Explanation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XkS1pbAcc0TYWjl14HeZ6SMLWgPVd_vf
"""

import pickle
token_score = pickle.load(open( "166samples_6dim.pkl", "rb" ) ) #635samples_6dim.pkl

text = ""
for token, shade in token_score.items():
        # print(token,":",shade)
        # shade = int(255 * score)  # calculate shade between 0 and 255
        if shade!=0:
          color = f"\033[48;2;{shade*150};0;0m"  # create color with specified shade of red
          text += f"{color}{token}\033[0m "  # add color to token and append to text
        else:
          color = f"\033[48;2;{(255-shade)*150};255;255m"  # create color with specified shade of red
          text += f"{color}{token}\033[0m "

        # f.write(f'{text}\n\n')
print(text)

